# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cffc9d40caf0a05f713bb4ec21312aa576dc55eabd2ba1c454ce5a6f99db76cfb8b51425c477db9d0b3f7920626e3e88c6f990162f7a9bbcc7663f87b1c700d6

test:
  secret_key_base: d23e2e39fbacabb9fb2c536c17374795bc11853a777d282728767a979f34360b98573aca2e6a1a1c7c292ecbfdf51b96228af8549a72e9a99104988ce09daea2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
